name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@tt04
        env:
          OPENLANE_TAG: 2023.06.26
          OPENLANE_IMAGE_NAME: efabless/openlane:3bc9d02d0b34ad032921553e512fbe4bebf1d833
          OPENLANE_ROOT: /home/runner/openlane

  viewer:
    needs: gds
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@tt04
